### ISSUE TITLE
Kindly add heroku support

### ISSUE THREAD

**Issue by rsoorajs** [mattprocoder/PHP-Temporary-Email#1]
kindly add heroku support

**Comment by rsoorajs** [comment]
also change code to php7. php5 is outdated,almost hosting sites doesnt accept php5 codes

**Comment by rsoorajs** [comment]
put a heroku deploy button will help to use your code easier

**Comment by mattprocoder** [comment]
Don't have much time currently, will definitely look into it once i do thought.

**Comment by rsoorajs** [comment]
i tried to hosted on ubuntu server and port forwarded with ngrok and still it doesnt worked.thats why i am asking you to add heroku deploy button.

![IMG20200628172521](https://user-images.githubusercontent.com/20116017/85964489-79c0b100-b9d7-11ea-812a-d0502577175e.jpg)

**Comment by rsoorajs** [comment]
![IMG20200628172513](https://user-images.githubusercontent.com/20116017/85964648-05d2d880-b9d8-11ea-95bf-72fcb69e53e9.jpg)

**Comment by rsoorajs** [comment]
see i set everything and installed php7.3-imap extention.still the email is not coming..

**Comment by telegrambotdev** [comment]
![Screenshot_2020-06-26-20-29-03-50](https://user-images.githubusercontent.com/20116017/85965889-d1f9b200-b9db-11ea-84bd-1d170442b86e.png)
![Screenshot_2020-06-26-19-54-49-46](https://user-images.githubusercontent.com/20116017/85965892-d45c0c00-b9db-11ea-9c70-f5115b0c41e8.png)
![Screenshot_2020-06-26-19-54-43-29](https://user-images.githubusercontent.com/20116017/85965897-d6be6600-b9db-11ea-9c12-d0d9b09d7325.png)


see i am getting imap authentification error while i hosted this code on heroku.(heroku only supports php7 or greater)

if you can add a deploy button..that will be appreciated.it will not take that much time.

**Comment by rsoorajs** [comment]
![Screenshot_2020-06-26-19-54-49-46](https://user-images.githubusercontent.com/20116017/85966070-5815f880-b9dc-11ea-81e2-dcc7f0668e95.png)

**Comment by rsoorajs** [comment]
this is the log of heroku.its showing imap auth error.(heroku only support php7 or greater)

so kindly add a heroku deploy button also include `php7.3-imap` in `composer.json` and `composer.lock` as like the below..anyway your project is awsome.

**Comment by rsoorajs** [comment]
![IMG_20200629_075048_113](https://user-images.githubusercontent.com/20116017/85966483-8cd67f80-b9dd-11ea-9653-a44011bd0f5a.jpg)

**Comment by rsoorajs** [comment]
Also read this if you are going to make a heroku support

https://devcenter.heroku.com/articles/heroku-button

**Comment by mattprocoder** [comment]
I think you have wrongly configured IMAP, however I'll do what you've recommended (I'll try) as soon as it's possible for me.

**Comment by rsoorajs** [comment]
![IMG_20200630_081218_001](https://user-images.githubusercontent.com/20116017/86077385-801f5d80-baa9-11ea-9c52-b7f9baf706df.jpg)

i put my imap configuration like this..still i donno whats wrong..If gmail is not suitable for fake mail can you refer some email provider with the sample config ?

Anyway thanks for your friendly reply and waiting for the heroku button.Thanks

**Comment by mattprocoder** [comment]
Gmail definitely isn't suitable for this, you need catchall email and thus your own domain.
I currently don't or can't think about any free to use catchall email provider, unfortunately.
